# Generated by Django 4.2 on 2023-04-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iata', '0002_iata_created_on_iata_updated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='iata',
            name='detailed_name',
            field=models.CharField(default='', max_length=256),
        ),
    ]
