# Generated by Django 4.2 on 2023-04-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='outgoing_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='flight',
            name='passenger_count',
            field=models.IntegerField(default=None),
        ),
    ]
