# Generated by Django 4.2 on 2023-04-19 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iata', '0003_iata_detailed_name'),
        ('flight', '0003_alter_flight_outgoing_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='fk_departure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='flight_departure', to='iata.iata'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='fk_destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='flight_destination', to='iata.iata'),
        ),
    ]
