version: "3.8"

services:
  amadeus_python:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 12345:8000
    env_file:
      - ./.env.dev
    depends_on:
      - amadeus_postgres

  amadeus_postgres:
    image: postgres:15-alpine3.17
    volumes:
      - postgresql_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=amadeus_user
      - POSTGRES_DB=amadeus_db
      - POSTGRES_PASSWORD=amadeus_password
    ports:
      - 5432:5432

volumes:
  postgresql_data:
