# curl "https://test.api.amadeus.com/v1/security/oauth2/token" \
#      -H "Content-Type: application/x-www-form-urlencoded" \
#      -d "grant_type=client_credentials&client_id={client_id}&client_secret={client_secret}"

# {
#     "type": "amadeusOAuth2Token",
#     "username": "foo@bar.com",
#     "application_name": "BetaTest_foobar",
#     "client_id": "3sY9VNvXIjyJYd5mmOtOzJLuL1BzJBBp",
#     "token_type": "Bearer",
#     "access_token": "CpjU0sEenniHCgPDrndzOSWFk5mN",
#     "expires_in": 1799,
#     "state": "approved",
#     "scope": ""
# }
