# Generated by Django 4.2 on 2023-04-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0002_connection_created_on_connection_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='arrival_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='departure_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='duration',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='number_of_stops',
            field=models.IntegerField(default=0),
        ),
    ]
