# Generated by Django 4.2 on 2023-04-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0003_alter_connection_arrival_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='arrival_terminal',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='departure_terminal',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
