# Generated by Django 4.2 on 2023-04-19 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iata', '0003_iata_detailed_name'),
        ('connection', '0005_alter_connection_number_of_stops'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='fk_connection_departure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='connection_departure', to='iata.iata'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='fk_connection_destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='connection_destination', to='iata.iata'),
        ),
    ]
